services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - db-auth:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

volumes:
  db-auth: